name: Nightly Build

on:
  schedule:
    - cron: '45 18 * * *' # Daily
#  push: # for build testing purpose, to be deleted
#    branches: [test-check-commit]

jobs:
  build:
    name: Run Nightly Build in PST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

#      - name: Set Timezone to PST
#        run: sudo timedatectl set-timezone America/Los_Angeles

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Run Docker on Ubuntu
        run: docker-compose up -d --build

      - name: Run Tests in the Container
        run: docker-compose exec -T web pytest

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: |
#            tiansigu/fastapi-tiansi

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: tiansigu/fastapi-tiansi:latest